"""Hand-built fixtures with known, hand-checkable answers.

Every number the analysis tests assert against can be verified with a
calculator from these series -- that is the point. Fixtures generated by the
same code under test would prove nothing.
"""

from __future__ import annotations

import pandas as pd


def frame_from_closes(closes, start="2026-01-05") -> pd.DataFrame:
    """Build an OHLCV frame on consecutive business days from close prices."""
    index = pd.bdate_range(start=start, periods=len(closes), name="date")
    series = pd.Series([float(c) for c in closes], index=index)
    return pd.DataFrame(
        {
            "open": series,
            "high": series * 1.01,
            "low": series * 0.99,
            "close": series,
            "volume": 1_000_000.0,
        }
    )


#: +10%, -50/110, ... chosen so returns are exact fractions.
SIMPLE_CLOSES = [100.0, 110.0, 121.0, 133.1]

#: Rises to 120, falls to 60 (max drawdown -50%), partially recovers.
DRAWDOWN_CLOSES = [100.0, 120.0, 90.0, 60.0, 80.0]

#: Flat 1% steps with one violent day -- exactly one obvious outlier.
ANOMALY_CLOSES = [100.0, 101.0, 102.01, 103.03, 104.06, 135.0, 136.35, 137.71, 139.09]


def alpha_vantage_payload(closes, symbol="TEST", start="2026-01-05") -> dict:
    """Wrap closes in the exact envelope Alpha Vantage returns (newest first)."""
    frame = frame_from_closes(closes, start=start)
    series = {}
    for date, row in frame.iloc[::-1].iterrows():
        series[date.strftime("%Y-%m-%d")] = {
            "1. open": f"{row['open']:.4f}",
            "2. high": f"{row['high']:.4f}",
            "3. low": f"{row['low']:.4f}",
            "4. close": f"{row['close']:.4f}",
            "5. volume": str(int(row["volume"])),
        }
    return {
        "Meta Data": {"2. Symbol": symbol, "5. Time Zone": "US/Eastern"},
        "Time Series (Daily)": series,
    }


RATE_LIMIT_PAYLOAD = {
    "Note": (
        "Thank you for using Alpha Vantage! Our standard API call frequency is "
        "5 calls per minute and 500 calls per day."
    )
}

INFORMATION_RATE_LIMIT_PAYLOAD = {
    "Information": (
        "We have detected your API key and our standard API rate limit is 25 "
        "requests per day."
    )
}

UNKNOWN_SYMBOL_PAYLOAD = {
    "Error Message": (
        "Invalid API call. Please retry or visit the documentation for TIME_SERIES_DAILY."
    )
}
